name: Push

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py
      - uses: actions/upload-artifact@v2
        with:
          name: coverage.${{ matrix.python }}
          path: .tox/.coverage.py

  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Restore coverage artifacts
        run: |
          mkdir .tox
          ls artifacts | while read -r name; do cp "artifacts/$name/.coverage.py" ".tox/.$name"; done
      - name: Run Tox
        run: tox -e coverage
      - uses: actions/upload-artifact@v2
        with:
          name: coverage report
          path: htmlcov

  build:
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: pip install wheel
      - name: Build dist
        run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  release:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Publish to Test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
